// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRVx9M2JySee8fzLur5ssUBT0KudTJM3o',
    appId: '1:56851153328:web:f5656da66dd08ac9be9675',
    messagingSenderId: '56851153328',
    projectId: 'chat-app-3fb15',
    authDomain: 'chat-app-3fb15.firebaseapp.com',
    databaseURL: 'https://chat-app-3fb15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-3fb15.appspot.com',
    measurementId: 'G-9M0SQ4R69J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCItpoOntShX9IRbSv0PE164GOmlzKGtMk',
    appId: '1:56851153328:android:005e3b5a0cffc2ffbe9675',
    messagingSenderId: '56851153328',
    projectId: 'chat-app-3fb15',
    databaseURL: 'https://chat-app-3fb15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-3fb15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqDDkWd06J6JAvyn05g6xQ6-p2_NsCK3o',
    appId: '1:56851153328:ios:f208dea3c4af2fcabe9675',
    messagingSenderId: '56851153328',
    projectId: 'chat-app-3fb15',
    databaseURL: 'https://chat-app-3fb15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-3fb15.appspot.com',
    iosClientId: '56851153328-80ov73oa981jqsmskagia8u277ph66ca.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqDDkWd06J6JAvyn05g6xQ6-p2_NsCK3o',
    appId: '1:56851153328:ios:529304d96fae2f58be9675',
    messagingSenderId: '56851153328',
    projectId: 'chat-app-3fb15',
    databaseURL: 'https://chat-app-3fb15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-3fb15.appspot.com',
    iosClientId: '56851153328-0msh1vg8i2u833oolphoemehset5413c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp11.RunnerTests',
  );
}
